export const SET_ARTICLES = 'SET_ARTICLES'
export const SET_ARTICLE = 'SET_ARTICLE'
export const UNSET_ARTICLE = 'UNSET_ARTICLE'

export const SET_APP_LOADING = 'SET_APP_LOADING'
export const UNSET_APP_LOADING = 'UNSET_APP_LOADING'