// ARTICLE
export const SET_ARTICLES = 'SET_ARTICLES'
export const SET_ARTICLE = 'SET_ARTICLE'

// AUTH
export const AUTH_STARTED = 'AUTH_STARTED'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'

// TAG
export const SET_TAGS = 'SET_TAGS'

// COMMONS
export const SET_APP_LOADING = 'SET_APP_LOADING'
export const UNSET_APP_LOADING = 'UNSET_APP_LOADING'
export const SET_ARTICLES_COUNT = 'SET_ARTICLES_COUNT'
export const UNSET_ARTICLES_COUNT = 'UNSET_ARTICLES_COUNT'
